# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: data-tests

jobs:
  data-tests:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          install.packages(c("remotes"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Run tests
        run: Rscript testthat.R
      - name: Check for new files
        id: check_new_files
        run: |
          if [[ -z "$(git status --porcelain)" ]] ; then 
            echo "Git status is empty"
            echo "::set-output name=diff::FALSE"
          else 
            echo "::set-output name=diff::TRUE"
          fi
      - name: Print flag
        run: |
          echo ${{ steps.check_new_files.outputs.diff }}
      - name: Commit any changes
        if steps.check_new_files.outputs.diff == 'TRUE'
        run: |      
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add error report"
      - name: Push any changes
        if steps.check_new_files.outputs.diff == 'TRUE'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}        