# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    paths:
      - 'data/**'
      - 'resources/raw_data/**'
      - 'Rscripts/survey_forms/create_master_csv_2021_and_after.R'
      - 'Rscripts/Generate_reports.R'
      - 'Rscripts/Generate_warnings.R'
      - 'README.Rmd'
  pull_request:
    paths:
      - 'data/**'
      - 'resources/raw_data/**'
      - 'Rscripts/survey_forms/create_master_csv_2021_and_after.R'
      - 'Rscripts/Generate_reports.R'
      - 'Rscripts/Generate_warnings.R'
      - 'README.Rmd'
      
name: QA_QC_checks

jobs:
  data-tests:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: |
          options(crayon.enabled = TRUE)
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
        
      - name: Create master CSV from raw data forms (only for 2021 and after)
        id: create_master_csv
        run: |
          source("Rscripts/survey_forms/create_master_csv_2021_and_after.R")
        shell: Rscript {0}     
        
      - name: Generate error reports
        id: generate_error_reports
        run: |
          source("Rscripts/Generate_reports.R")
        shell: Rscript {0}
        
      - name: Generate warning reports
        id: generate_warning_reports
        run: |
          source("Rscripts/Generate_warnings.R")
        shell: Rscript {0}
        
      - name: Update README dashboard
        id: update_README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'

      - name: Commit new files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add --all
          git commit -am "add data"
          git push
          
      - name: Are there any data collection errors?
        run: Rscript testthat.R